### ISSUE TITLE
Should we recommend using 18f's US Web Design Standards?

### ISSUE THREAD

**Issue by loganpowell** [annaawang/templates#1]
Looks like you're using [US Web Design Standards](https://standards.usa.gov/components/) for your styles... good on you! Will this be a recommendation for us? Please say yes.

**Comment by loganpowell** [comment]
List of others who've adopted the standard: https://github.com/18F/web-design-standards/blob/develop/WHO_IS_USING_USWDS.md

**Comment by annaawang** [comment]
Logan... YES!! I have promoted the web design standards to Jeff, Lisa, Michele, Stephen Buckner, and the Accenture folks. One of the goals for this project was also to demonstrate what the standards could look like as applied to the Census Bureau versus using the CEDSCI pattern library. :)
